export const  CATEGORY_SET = "CATEGORY_SET";
export const  CATEGORIES_SET = "CATEGORIES_SET";
export const  CATEGORY_DELETE = "CATEGORY_DELETE";
export const CATEGORY_STATE_CLEAR = "CATEGORY_STATE_CLEAR";

export const COMMON_ERROR_SET = "COMMON_ERROR_SET";
export const COMMON_MESSAGE_SET = "COMMON_MESSAGE_SET";
export const COMMON_LOADING_SET = "COMMON_LOADING_SET";

export const  PRODUCT_SET = "PRODUCT_SET";
export const  PRODUCTS_SET = "PRODUCTS_SET";
export const  PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_STATE_CLEAR = "PRODUCT_STATE_CLEAR";